[package]
name = "pqdid-r0-relation"
version = "0.1.0"
edition = "2021"
license = "UNLICENSED"

[dependencies]
sha3 = "=0.10.8"

[features]
diagnostics = ["dep:risc0-zkvm"]
components = []

[dependencies.risc0-zkvm]
version = "=3.0.6"
default-features = false
features = ["std", "disable-dev-mode"]
optional = true
